circle_gen:
  ros__parameters:
    # rate
    rate_ros: 100.0

    # model
    model_base: "base_link"
    model_odom: "odom"

    # circle
    circle_center:
      - 0.0
      - 0.0
    circle_radius: 2.0
    arc_length: 0.2
    circle_inverse_flag: false
