circle_gen:
  ros__parameters:
    # rate
    rate_ros: 100.0

    # model
    model_base: "base_link"
    model_odom: "odom"

    # circle
    circle_center:
      - 0.0
      - 0.0
    circle_radius: 1.0
    circle_interpolation: 3000
    circle_switch_dist: 0.1
    circle_inverse_flag: false
